name: Board meetings additional config
description: Provides ECK entity types and fields for them
package: 360biz
type: module
core_version_requirement: ^8.8 || ^9
version: '8.x-1.0'
dependencies:
  - drupal:ckeditor_accordion
  - drupal:eck