display:
  default:
    display_title: Основной
    display_options:
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      fields:
        field_flexslider_example_image:
          separator: ', '
  page_1:
    display_options:
      fields:
        field_flexslider_example_image:
          separator: ', '
        title:
          separator: ', '
  page_2:
    display_options:
      fields:
        field_flexslider_example_image:
          separator: ', '
  page_6:
    display_options:
      fields:
        field_flexslider_example_image:
          separator: ', '
        title:
          separator: ', '
