display:
  default:
    display_title: Основной
    display_options:
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      pager:
        options:
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
          tags:
            previous: '‹ предыдущая'
            next: 'следующая ›'
            first: '« первая'
            last: 'последняя »'
      fields:
        node_bulk_form:
          label: 'Форма массовых операций с материалами'
          action_title: 'С выделенным'
        title:
          label: Проблема
        simplenews_issue:
          label: Рассылка
          separator: ', '
        status:
          label: Опубликовано
          separator: ', '
        created:
          label: Обновлено
        operations:
          label: 'Ссылки операций'
      filters:
        simplenews_issue_target_id_1:
          expose:
            label: Рассылка
  page_1:
    display_title: Страница
