title: 'Связаться с нами'
settings:
  confirmation_message: 'Ваше сообщение отправлено.'
handlers:
  email_confirmation:
    label: 'Подтверждение почтой'
  email_notification:
    label: 'Уведомления по email'
