title: Контакт
elements: |-
  department:
    '#type': select
    '#title': Department
    '#options':
      - 'Bill Inquiries/Customer Services'
      - 'Water Quality'
      - 'Water Use Efficiency'
      - 'Backflow/Cross Connection Control'
      - 'Media Contact'
      - 'General Manager'
      - 'Business Administrator'
      - 'Executive Assistant to the General Manager'
      - 'Administrative Services'
      - 'Customer Services'
      - Engineering
      - 'Financial Services'
      - 'Human Resources'
      - 'Public Affairs'
      - 'Water Operations'
      - 'Water Policy'
    '#required': true
  flexbox:
    '#type': webform_flexbox
    name:
      '#type': textfield
      '#title': 'Full Name'
      '#required': true
      '#default_value': '[current-user:display-name]'
    email:
      '#type': email
      '#title': 'Email Address'
      '#required': true
      '#default_value': '[current-user:mail]'
  flexbox_01:
    '#type': webform_flexbox
    full_address:
      '#type': textfield
      '#title': 'Full Address'
      '#required': true
    phone_number:
      '#type': tel
      '#title': 'Phone Number'
  subject:
    '#title': Subject
    '#type': textfield
    '#required': true
    '#test': 'Testing contact webform from [site:name]'
  message:
    '#title': Message
    '#type': textarea
    '#required': true
    '#test': 'Please ignore this email.'
  actions:
    '#type': webform_actions
    '#title': 'Submit button(s)'
    '#submit__label': 'Send message'
settings:
  confirmation_message: 'Ваше сообщение отправлено.'
