display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'último »'
      fields:
        node_bulk_form:
          label: 'Formulario de operaciones masivas de nodo'
          action_title: 'Con selección'
        title:
          label: Incidencia
        simplenews_issue:
          label: Boletín
          separator: ', '
        status:
          label: Publicado
          separator: ', '
        created:
          label: Actualizado
        send_status:
          label: 'Estado de envío'
        operations:
          label: 'Enlaces de operación'
      filters:
        simplenews_issue_target_id_1:
          expose:
            label: Boletín
  page_1:
    display_title: Página
