display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        sid:
          label: ID
        ip_address:
          label: 'Dirección IP'
  page_1:
    display_title: Página
    display_options:
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        sid:
          label: ID
        ip_address:
          label: 'Dirección IP'
  page_2:
    display_options:
      arguments:
        sid:
          exception:
            title: Todo(s)
      fields:
        sid:
          label: ID
        ip_address:
          label: 'Dirección IP'
