display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          separator: ', '
        field_alert_type:
          separator: ', '
        body:
          separator: ', '
  block_1:
    display_title: Bloque
