module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  asset_injector: 0
  autocomplete_inputs: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  bootstrap_paragraphs: 0
  bp_card: 0
  breakpoint: 0
  captcha: 0
  civic_mega_menu: 0
  civic_theme_docs: 0
  ckeditor: 0
  ckeditor_accordion: 0
  ckeditor_bootstrap_buttons: 0
  ckeditor_bootstrap_grid: 0
  ckeditor_bootstrap_grid_extended: 0
  ckeditor_bs_grid: 0
  ckeditor_templates: 0
  ckeditor_youtube: 0
  color: 0
  color_field: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  current_page_crumb: 0
  date_recur: 0
  date_recur_modular: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  editor_advanced_link: 0
  entity_class_formatter: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flexslider: 0
  flexslider_example: 0
  flexslider_fields: 0
  flexslider_views: 0
  fontawesome: 0
  fontawesome_menu_icons: 0
  geolocation_filter: 0
  google_analytics: 0
  gtranslate: 0
  help: 0
  history: 0
  hover_effects: 0
  image: 0
  image_link_formatter: 0
  imce: 0
  inline_entity_form: 0
  insert: 0
  insert_view_adv: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  lang_dropdown: 0
  language: 0
  language_switcher_menu: 0
  layout_bg: 0
  layout_bg_bricks: 0
  layout_bg_paragraph: 0
  layout_bg_thumb_over_thumb: 0
  layout_builder: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_attributes: 0
  locale: 0
  mail_safety: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_breadcrumb: 0
  menu_translate: 0
  menu_ui: 0
  mesa_events: 0
  mesa_moderation: 0
  mesa_moderation_reminder: 0
  mimemail: 0
  mod_schedule_pub: 0
  node: 0
  options: 0
  owlcarousel: 0
  page_cache: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  pdf_to_image_preview: 0
  pdfview: 0
  private_pages: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  rename_admin_paths: 0
  responsive_image: 0
  rest: 0
  rules: 0
  scheduler: 0
  scheduler_rules_integration: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_menu_icons: 0
  simple_timeline: 0
  simplenews: 0
  sitemap: 0
  slick: 0
  slick_paragraphs: 0
  slick_ui: 0
  smtp: 0
  superfish: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  text_alert: 0
  text_field_formatter: 0
  toggle_admin: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  typed_data: 0
  ultimate_cron: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_autosubmit: 0
  views_bulk_operations: 0
  views_conditional: 0
  views_data_export: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_simplenews_handler: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  civic: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
