session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ar: ar
    zh-hans: zh-hans
    ru: ru
  domains:
    en: ''
    es: ''
    ar: ''
    zh-hans: ''
    ru: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
