smtp_on: false
smtp_host: smtp.mailgun.org
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: postmaster@mg.360-biz.com
smtp_password: 284398f99edd49a173ee9b1f84a3605d-7238b007-1c5ccad8
smtp_from: no-reply-web@semi-kinetics.com
smtp_fromname: 'Semi-Kinetics Information'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: true
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
