<?php

function mesa_moderation_views_pre_render($view) {

  if ($view->id() == 'moderation_notifications') {

    $users_present = [];

    foreach ($view->result as $item) {
      $node = $item->_entity;

      if ($node->hasField('field_user')) {
        $users_value = $node->get('field_user')->getValue();

        if ($users_value) {
          foreach ($users_value as $user_item) {
            $users_present[$user_item['target_id']] = $user_item['target_id'];
          }
        }
      }
    }

    $users_loaded = \Drupal\user\Entity\User::loadMultiple(array_values($users_present));

    $view->users_loaded = $users_loaded;
  }
}

function mesa_moderation_form_alter(&$form, &$form_state, $form_id) {


  if ($form_id == 'rules_expression_edit') {
    $fields_needed = [
      'to', 'subject', 'message', 'reply', 'language'
    ];

    $field_present = [];
    if (!empty($form['context_definitions'])) {
      foreach ($form['context_definitions'] as $label => $field) {
        if (!is_numeric(strpos($label, '#'))) {
          $fields_present[] = $label;
        }
      }

      if ($fields_needed == $fields_needed) {

        if (!empty($form['context_definitions']['message']['setting']) && empty($form['context_definitions']['message']['setting']['#attributes']['data-autocomplete-path'])) {
          $form['context_definitions']['message']['setting']['#type'] = 'textarea';
        }
      }
    }
  }


  if ($form_id == 'views_exposed_form') {

    if (strpos($form['#id'], 'views-exposed-form-moderation-notifications') === 0) {
      $form['#attached']['library'][] = 'mesa_moderation/mesa_moderation_events_form';
    }
  }
}

function mesa_moderation_preprocess_user(&$variables) {

  $block_manager = \Drupal::service('plugin.manager.block');

  $notifications_block = $block_manager->createInstance('views_block:moderation_notifications-block_1',
      []);

  if ($notifications_block) {
    $variables['content']['moderation_notifications'] = [
      '#type'           => 'container',
      '#attributes'     => [
        'class' => ["moderation_notifications_view_wrapper"],
      ],
      "element-content" => $notifications_block->build(),
      '#weight'         => 0,
    ];
  }
}

/**
 * Implements hook_views_data_alter().
 */
function mesa_moderation_views_data_alter(array &$data) {

  $data['node_revision']['related_users'] = array(
    'title' => t('Related users'),
    'field' => array(
      'title' => t('Related users'),
      'help'  => t('Related users.'),
      'id'    => 'related_users',
    ),
  );

  $data['node']['news_category_from_current_node'] = array(
    'title' => t('News category from current node'),
    'field' => array(
      'title' => t('News category from current node'),
      'help'  => t('News category from current node.'),
      'id'    => 'news_category_from_current_node',
    ),
  );
}
