<?php

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\OpenOffCanvasDialogCommand;
use Drupal\Core\Ajax\DataCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\InvokeCommand;

function mesa_events_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $type = $entity->getEntityTypeId();

  if ($type == 'node' && $entity->hasField('field_event_title_template')) {

    $template_val = $entity->get('field_event_title_template')->getValue();

    if (!empty($template_val[0]['target_id'])) {
      $tid = $template_val[0]['target_id'];

      $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid);

      if ($term) {
        $term_name = $term->get('name')->getValue();

        if ($term_name) {
          $term_name = $term_name[0]['value'];

          if ($entity->hasField('field_event_date_for_title')) {

            $date_val = $entity->get('field_event_date_for_title')->getValue();

            if ($date_val) {
              $date_val = strtotime($date_val[0]['value']);

              $other_terms = [];

              if ($entity->hasField('field_event_category1')) {
                $cat_vals = $entity->get('field_event_category')->getValue();

                foreach ($cat_vals as $cat_val) {
                  $cat_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($cat_val['target_id']);

                  if ($cat_term) {
                    $cat_title = me_reset_m($cat_term->get('name')->getValue());

                    $other_terms[] = $cat_title;
                  }
                }
              }



              $generated_title = mesa_events_generate_title($term_name,
                  $date_val, $other_terms);

              if ($generated_title) {
                $entity->set('title', $generated_title);
              }
            }
          }
        }
      }
    }
  }
}

function mesa_events_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  $type = $entity->getEntityTypeId();
  if ($type == 'taxonomy_term' && $entity->bundle() == 'event_title_templates') {

    $nids = \Drupal::entityQuery('node')
        ->condition('field_event_title_template', $entity->id())
        ->execute();

    if ($nids) {
      foreach ($nids as $nid) {
        $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
        $node->save();
      }
    }
  }
}

function mesa_events_generate_title($title_term_name, $date, $other_terms = []) {
  /* $date_component = preg_match('~(\[.*?\])~', $template, $matches);
    if (!empty($matches[0])) {
    $date_component = $matches[0];

    $date_formatted = date(str_replace(['[', ']'], '', $date_component), $date);

    $template = str_replace($date_component, $date_formatted, $template);
    }
   */

  $title_term_name = date('m/d/Y', $date) . ' ' . $title_term_name;

  if ($other_terms) {
    $title_term_name .= ', ' . implode(', ', $other_terms);
  }

  return $title_term_name;
}

/**
 * Implements hook_form_alter().
 */
function mesa_events_form_alter(&$form, &$form_state, $form_id) {




  if ($form_id == 'node_event_form') {
    $form['title']['widget'][0]['value']['#default_value'] = '_';
  }

  if ($form_id == 'node_event_edit_form') {

    //ksm(func_get_args());

    $nid = explode('/', $_SERVER['REQUEST_URI'])[2];

    $form['notifications'] = [
      '#type'       => 'details',
      '#title'      => t('Notifications'),
      '#attributes' => [
        'class' => ['notifications-wrapper'],
      ],
      '#weight'     => 110,
      '#open'       => TRUE,
    ];

    $form['notifications']['left'] = [
      '#type'       => 'container',
      '#attributes' => [
        'class' => 'notifications-left',
      ],
    ];

    $list_ids = \Drupal::entityQuery('mails_list')
        //->condition('field_event_title_template', $entity->id())
        ->execute();

    $lists = \Drupal::entityTypeManager()->getStorage('mails_list')->loadMultiple($list_ids);

    $lists_options = [];

    foreach ($lists as $list) {

      $list_title = $list->get('title')->getValue();

      $lists_options[$list->id()] = $list_title[0]['value'];
    }


    $form['notifications']['left']['notifications_list'] = [
      '#type'    => 'select',
      '#title'   => t('List'),
      '#options' => $lists_options,
    ];

    $templates_ids = \Drupal::entityQuery('notification_template')
        //->condition('field_event_title_template', $entity->id())
        ->execute();

    $templates = \Drupal::entityTypeManager()->getStorage('notification_template')->loadMultiple($templates_ids);

    $templates_options = [];

    $templates_data = [];

    foreach ($templates as $template) {

      $template_title = $template->get('title')->getValue();

      $template_body = me_reset_m($template->get('field_nt_body')->getValue());

      $template_subject = me_reset_m($template->get('field_nt_subject')->getValue());

      $templates_options[$template->id()] = $template_title[0]['value'];

      $templates_data[$template->id()] = [
        'body'    => $template_body,
        'subject' => $template_subject,
      ];
    }

    $form['#attached']['drupalSettings']['notifications_templates'] = $templates_data;
    $form['#attached']['library'][] = 'mesa_events/mesa_events_notification_form';

    $form['notifications']['left']['notifications_template'] = [
      '#type'    => 'select',
      '#title'   => t('Template'),
      '#options' => $templates_options,
    ];

    $form['notifications']['left']['notifications_subject'] = [
      '#type'  => 'textfield',
      '#title' => t('Subject'),
    ];

    $form['notifications']['left']['notifications_body'] = [
      '#type'  => 'textarea',
      '#title' => t('Email content'),
    ];

    $form['notifications']['left']['notifications_test_mail'] = [
      '#type'  => 'email',
      '#title' => t('Send Test To'),
    ];

    $form['notifications']['left']['notification_send'] = [
      '#type'   => 'submit',
      '#value'  => t('Send'),
      '#submit' => [
       // 'ggg',
      ],
      '#ajax'   => [
        'callback' => 'mesa_events_notification_send_ajax',
        'effect'   => 'fade',
      ],
    ];

    $form['notifications']['left']['nid'] = [
      '#type'  => 'hidden',
      '#value' => $nid,
    ];

    $form['notifications']['right'] = [
      '#type'       => 'container',
      '#attributes' => [
        'class' => 'notifications-right',
      ],
    ];

    //ksm($form);
    //ksm($form_state);

    $form['notifications']['right']['view'] = [
      views_embed_view('notifications', 'default', $nid),
    ];
  }
}

function mesa_events_notification_send_ajax(array &$form, $form_state) {
  $response = new AjaxResponse();

  $values = $form_state->getValues();

  $to = $values['notifications_list'];

  if (!empty($values['notifications_test_mail'])) {
    $to = $values['notifications_test_mail'];
  }

  mesa_events_send_notification($to, $values['notifications_subject'],
      $values['notifications_body'], $values['nid']);

  // Update options for entity type bundles.
  $response->addCommand(new ReplaceCommand(
          '#edit-right .views-element-container',
          views_embed_view('notifications', 'default', $values['nid'])
  ));

  return $response;
}

/**
 * Helper function that resets arrays of any deepness and accepts 
 * not only variables as an argument.
 */
function me_reset_m($var, $num = 99) {
  for ($i = 0; $i < $num; $i++) {

    if (is_array($var)) {
      $var = reset($var);
    }
    else {
      return $var;
    }
  }
  return $var;
}

function mesa_events_send_notification($to, $subject, $message, $event_id) {

  $mailManager = \Drupal::service('plugin.manager.mail');
  $module = 'mesa_events';
  $key = 'event_notification';

  $list_id = NULL;

  if (!is_numeric($to)) {
    $to_array = [$to];
  }
  else {
    $to_array = [];

    $list = \Drupal::entityTypeManager()->getStorage('mails_list')->load($to);

    if ($list) {

      $list_id = $to;

      $emails_list = me_reset_m($list->get('field_mails_list_addresses')->getValue());

      if ($emails_list) {
        $emails_list = explode("\n", $emails_list);

        if ($emails_list) {
          $to_array = $emails_list;
        }
      }
    }
  }

  $event_node = \Drupal::entityTypeManager()->getStorage('node')->load($event_id);

  $event_title = me_reset_m($event_node->get('title')->getValue());

  $message = str_replace('{{ title }}', $event_title, $message);
  $message = str_replace('{{ nid }}', $event_id, $message);

  $params['message'] = $message;
  $params['subject'] = $subject;

  //$langcode = $tuser->getPreferredLangcode();

  $langcode = 'en';

  $send = true;

  foreach ($to_array as $to) {
    
    $message_local = str_replace('{{ unsubscribe }}',
        mesa_events_generate_unsubscribe_link(1, $to), $message);
    
    
    $params['message'] = $message_local;
    
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL,
        $send);

    $notification = \Drupal::entityTypeManager()->getStorage('notification')->create([
      'type' => 'notification',
    ]);

    
    $notification->set('field_notification_body', $message_local);
    $notification->set('field_notification_subject', $subject);
    $notification->set('field_notification_receiver', $to);

    $notification->set('field_notification_event', $event_id);

    if ($list_id) {
      $notification->set('field_notification_list', $list_id);
    }

    $notification->save();
  }
}

function mesa_events_generate_unsubscribe_link($list_id, $email) {
  $link = 'mesawater_list_unsubscribe?email=' . $email . '&token=' . hash('sha256',
          $list_id . $email);

  return $link;
}

/**
 * Implements hook_mail().
 */
function mesa_events_mail($key, &$message, $params) {
  /* $options = array(
    'langcode' => $message['langcode'],
    ); */
  switch ($key) {
    case 'event_notification':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}

function mesa_events_list_subscribe($list_id, $email) {

  if (is_numeric($list_id)) {

    $list = \Drupal::entityTypeManager()->getStorage('mails_list')->load($list_id);

    if ($list) {

      $emails_list = me_reset_m($list->get('field_mails_list_addresses')->getValue());

      $emails_array = explode("\n", $emails_list);

      $emails_indexed = [];
      foreach ($emails_array as $email_item) {

        $email_item = trim($email_item);

        $emails_indexed[$email_item] = $email_item;
      }

      $emails_indexed[$email] = $email;

      $emails_list_reformed = implode("\n", $emails_indexed);

      $list->set('field_mails_list_addresses', $emails_list_reformed);

      $list->save();
    }
  }
}

function mesa_events_list_unsubscribe($list_id, $email) {
  if (is_numeric($list_id)) {

    $list = \Drupal::entityTypeManager()->getStorage('mails_list')->load($list_id);

    if ($list) {

      $emails_list = me_reset_m($list->get('field_mails_list_addresses')->getValue());

      $emails_array = explode("\n", $emails_list);

      $emails_indexed = [];
      foreach ($emails_array as $email_item) {

        $email_item = trim($email_item);

        $emails_indexed[$email_item] = $email_item;
      }

      if (isset($emails_indexed[$email])) {
        unset($emails_indexed[$email]);
      }

      $emails_list_reformed = implode("\n", $emails_indexed);

      $list->set('field_mails_list_addresses', $emails_list_reformed);

      $list->save();
    }
  }
}
