name: Board meetings main config
description: Main config files for node type and taxonomy vocabularies 
package: 360biz
type: module
core_version_requirement: ^8.8 || ^9
version: '8.x-1.0'
dependencies:
  - drupal:ckeditor_accordion